Считаем разницу истинных параметров прямой $a$ и $b$ и их оценок. Здесь также используются 2 варианта: с подавлением окрестности около локального максимума и без.

```{r}
library(Rcpp)
source("hough transform/hough_transform.r")



library(transport)
library(dplyr)
library(tibble)
```

Матрица изображения

```{r}
n_col = 100
n_row = 100

detectors <- list(
  function(m) cssa_detector(m, method="col.row"),
  function(m) cssa_detector(m, method="row.row"),
  intensity_detector,
  intensity_gradient_detector
)

matrix <- matrix(0, ncol=n_col, nrow=n_row) |> add.line(b=10) |> add.line(a=-0.5, b = 50)
noisy_matrix <- matrix |> add.noise(sigma=0.2)

```





Для начала подготовим функции для нахождения k максимумов с локальным подавлением вокруг максимума и без.


```{r}
library(tidyverse)
library(clue)


convert_ab_to_rho_theta <- function(a, b) {
  theta <- atan(-1 / a)
  rho   <- b * sin(theta)
  c(rho, theta)
}

# нахождение индексов k максимумов
find_k_max <- function(acc, k, qrho, qtheta, suppress = FALSE, window = 6) {
  acc_copy <- acc
  maxima <- list()
  
  for (i in seq_len(k)) {
    idx <- which(acc_copy == max(acc_copy), arr.ind = TRUE)[1, ]
    
    rho_val <- qrho[idx[1]]
    theta_val <- qtheta[idx[2]]
    maxima[[i]] <- c(rho = rho_val, theta = theta_val)
    
    if (suppress) {
      r_range <- max(1, idx[1] - window):min(nrow(acc_copy), idx[1] + window)
      c_range <- max(1, idx[2] - window):min(ncol(acc_copy), idx[2] + window)
      acc_copy[r_range, c_range] <- 0
    } else {
      acc_copy[idx[1], idx[2]] <- 0
    }
  }
  # plot.matrix(acc_copy)
  do.call(rbind, maxima)
  }

compute_err <- function(true, pred) {
  n_true <- nrow(true)
  n_pred <- nrow(pred)
  
  cost <- matrix(0, nrow = n_true, ncol = n_pred)
  for (i in 1:n_true) {
    for (j in 1:n_pred) {
      dr <- (true[i,1] - pred[j,1])^2
      dtheta <- atan2(
        sin(true[i,2] - pred[j,2]),
        cos(true[i,2] - pred[j,2])
      )^2
      cost[i,j] <- dr + dtheta
    }
  }
  
  assignment <- solve_LSAP(cost)
  pred_matched <- pred[assignment, , drop = FALSE]
  
  dr <- sum((true[,1] - pred_matched[,1])^2)
  dtheta <- sum(atan2(
    sin(true[,2] - pred_matched[,2]),
    cos(true[,2] - pred_matched[,2])
  )^2)
  
  return(c(dr = dr, dtheta = dtheta))
}

```

Вычисление
```{r}
# Rprof("a.out")
base_matrix <- matrix(0, ncol=n_col, nrow=n_row) |> 
  add.line(a=2, b=10) |> 
  add.line(a=-1, b=80) 

detector_names <- c("row.row", "col.row", 
                    "ht_intensity", "ht_gradient")



num_of_lines <- 2
max_iter <- 1
rho_step=0.3
theta_step = 0.003
w_size = 2*round(sqrt(n_col^2 + n_row^2))
w <- round(sqrt(w_size*pi/(rho_step*theta_step*9)))
results <- list()

true_lines <- rbind(
  convert_ab_to_rho_theta(2, 10),
  convert_ab_to_rho_theta(-1, 80)
)



for (d in seq_along(detectors)) {
  detector <- detectors[[d]]
  errors <- vector("list", max_iter)
  
  for (i in seq_len(max_iter)) {
    noisy_matrix <- base_matrix |> add.noise(sigma = 0.2)
    res <- make_accumulator(noisy_matrix, detector, rho_step=rho_step, theta_step=theta_step)
    
    
    
    
    pred_rhotheta <- find_k_max(res$accumulator, k = num_of_lines,
                                qrho = res$rho, qtheta = pi/2 - res$theta,
                                suppress = T, window = w )
    
    err <- compute_err(true_lines, pred_rhotheta)
    errors[[i]] <- err
  }
  
  err_matrix <- do.call(rbind, errors)
  mean_vals <- colMeans(err_matrix)
  
  results[[d]] <- tibble(
    detector = detector_names[d],
    rho_mean = mean_vals["dr"],
    theta_mean = mean_vals["dtheta"]
  )
}

df <- bind_rows(results)
print(df)
#Rprof(NULL)
#summaryRprof("a.out")
```
